export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

//User
export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER = 'GET_USER';

//Events
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_LOADING = 'GET_EVENTS_LOADING';

export const ADD_USER_EVENT_SUCCESS = 'ADD_USER_EVENT_SUCCESS';
export const ADD_USER_EVENT_FAIL = 'ADD_USER_EVENT_FAIL';
export const ADD_USER_EVENT_LOADING = 'ADD_USER_EVENT_LOADING';

export const GET_USER_EVENT_LOADING = 'GET_USER_EVENT_LOADING';
export const GET_USER_EVENT_SUCCESS = 'GET_USER_EVENT_SUCCESS';
export const GET_USER_EVENT_FAIL = 'GET_USER_EVENT_FAIL';

export const UPDATE_USER_EVENT_LOADING = 'UPDATE_USER_EVENT_LOADING';
export const UPDATE_USER_EVENT_SUCCESS = 'UPDATE_USER_EVENT_SUCCESS';
export const UPDATE_USER_EVENT_FAIL = 'UPDATE_USER_EVENT_FAIL';

export const DELETE_USER_EVENT_LOADING = 'DELETE_USER_EVENT_LOADING';
export const DELETE_USER_EVENT_SUCCESS = 'DELETE_USER_EVENT_SUCCESS';
export const DELETE_USER_EVENT_FAIL = 'DELETE_USER_EVENT_FAIL';

//Notes
export const ADD_NOTES_SUCCESS = 'ADD_NOTES_SUCCESS';
export const ADD_NOTES_FAIL = 'ADD_NOTES_FAIL';
export const ADD_NOTES_LOADING = 'ADD_NOTES_LOADING';

export const GET_NOTES_LOADING = 'GET_NOTES_LOADING';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL';

export const UPDATE_NOTES_LOADING = 'UPDATE_NOTES_LOADING';
export const UPDATE_NOTES_SUCCESS = 'UPDATE_NOTES_SUCCESS';
export const UPDATE_NOTES_FAIL = 'UPDATE_NOTES_FAIL';

export const DELETE_NOTES_LOADING = 'DELETE_NOTES_LOADING';
export const DELETE_NOTES_SUCCESS = 'DELETE_NOTES_SUCCESS';
export const DELETE_NOTES_FAIL = 'DELETE_NOTES_FAIL';
